order-port: 26733
raft-port: 27238
order-replication-factor: 3
order-batching-interval: 500ms
# order-ip-address: 127.0.0.1
order-ip-address: 192.168.64.40

data-port: 23282
data-replication-factor: 2
data-batching-interval: 500ms
# data-ip-address: 127.0.0.1
data-ip-address: 192.168.64.33
shards: 2

disc-port: 23472
# disc-ip-address: 127.0.0.1
disc-ip-address: 192.168.64.23

zk-port: 23222
zk-ip-address: 192.168.64.38
zk-servers:
  - 192.168.64.38
  - 192.168.64.30
  - 192.168.64.39
zids:
  - 0
  - 1
  - 2
# zk-ip-address: 127.0.0.1
zk-sleep-if-no-update: 100 #ms

zk-metadata-port: 23300

metadata-trim-threshold: 5000 
metadata-probe-frequency: 1000 # ms
metadata-trim-frequency: 2000 # ms

async-trie-update: true
disable-logs: true
parallel-bulk-aync-update: false