// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: zookeepermetadata.proto

package zookeepermetadata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ZooKeeperClient is the client API for ZooKeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZooKeeperClient interface {
	FetchOne(ctx context.Context, in *FetchOneRequest, opts ...grpc.CallOption) (*FetchOneResponse, error)
	FetchAll(ctx context.Context, in *FetchAllRequest, opts ...grpc.CallOption) (*FetchAllResponse, error)
}

type zooKeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewZooKeeperClient(cc grpc.ClientConnInterface) ZooKeeperClient {
	return &zooKeeperClient{cc}
}

func (c *zooKeeperClient) FetchOne(ctx context.Context, in *FetchOneRequest, opts ...grpc.CallOption) (*FetchOneResponse, error) {
	out := new(FetchOneResponse)
	err := c.cc.Invoke(ctx, "/zookeepermetadata.ZooKeeper/FetchOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zooKeeperClient) FetchAll(ctx context.Context, in *FetchAllRequest, opts ...grpc.CallOption) (*FetchAllResponse, error) {
	out := new(FetchAllResponse)
	err := c.cc.Invoke(ctx, "/zookeepermetadata.ZooKeeper/FetchAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZooKeeperServer is the server API for ZooKeeper service.
// All implementations must embed UnimplementedZooKeeperServer
// for forward compatibility
type ZooKeeperServer interface {
	FetchOne(context.Context, *FetchOneRequest) (*FetchOneResponse, error)
	FetchAll(context.Context, *FetchAllRequest) (*FetchAllResponse, error)
	mustEmbedUnimplementedZooKeeperServer()
}

// UnimplementedZooKeeperServer must be embedded to have forward compatible implementations.
type UnimplementedZooKeeperServer struct {
}

func (UnimplementedZooKeeperServer) FetchOne(context.Context, *FetchOneRequest) (*FetchOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchOne not implemented")
}
func (UnimplementedZooKeeperServer) FetchAll(context.Context, *FetchAllRequest) (*FetchAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchAll not implemented")
}
func (UnimplementedZooKeeperServer) mustEmbedUnimplementedZooKeeperServer() {}

// UnsafeZooKeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZooKeeperServer will
// result in compilation errors.
type UnsafeZooKeeperServer interface {
	mustEmbedUnimplementedZooKeeperServer()
}

func RegisterZooKeeperServer(s grpc.ServiceRegistrar, srv ZooKeeperServer) {
	s.RegisterService(&ZooKeeper_ServiceDesc, srv)
}

func _ZooKeeper_FetchOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZooKeeperServer).FetchOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zookeepermetadata.ZooKeeper/FetchOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZooKeeperServer).FetchOne(ctx, req.(*FetchOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZooKeeper_FetchAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZooKeeperServer).FetchAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zookeepermetadata.ZooKeeper/FetchAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZooKeeperServer).FetchAll(ctx, req.(*FetchAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZooKeeper_ServiceDesc is the grpc.ServiceDesc for ZooKeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZooKeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zookeepermetadata.ZooKeeper",
	HandlerType: (*ZooKeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchOne",
			Handler:    _ZooKeeper_FetchOne_Handler,
		},
		{
			MethodName: "FetchAll",
			Handler:    _ZooKeeper_FetchAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zookeepermetadata.proto",
}
