// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative zookeepermetadata.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: zookeepermetadata.proto

package zookeepermetadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId int32 `protobuf:"varint,1,opt,name=shardId,proto3" json:"shardId,omitempty"`
	GSN     int64 `protobuf:"varint,2,opt,name=GSN,proto3" json:"GSN,omitempty"`
}

func (x *MetadataListItem) Reset() {
	*x = MetadataListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zookeepermetadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataListItem) ProtoMessage() {}

func (x *MetadataListItem) ProtoReflect() protoreflect.Message {
	mi := &file_zookeepermetadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataListItem.ProtoReflect.Descriptor instead.
func (*MetadataListItem) Descriptor() ([]byte, []int) {
	return file_zookeepermetadata_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataListItem) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *MetadataListItem) GetGSN() int64 {
	if x != nil {
		return x.GSN
	}
	return 0
}

type FetchOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gsn int64 `protobuf:"varint,1,opt,name=gsn,proto3" json:"gsn,omitempty"`
}

func (x *FetchOneRequest) Reset() {
	*x = FetchOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zookeepermetadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOneRequest) ProtoMessage() {}

func (x *FetchOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zookeepermetadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOneRequest.ProtoReflect.Descriptor instead.
func (*FetchOneRequest) Descriptor() ([]byte, []int) {
	return file_zookeepermetadata_proto_rawDescGZIP(), []int{1}
}

func (x *FetchOneRequest) GetGsn() int64 {
	if x != nil {
		return x.Gsn
	}
	return 0
}

type FetchOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId int32 `protobuf:"varint,1,opt,name=shardId,proto3" json:"shardId,omitempty"`
}

func (x *FetchOneResponse) Reset() {
	*x = FetchOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zookeepermetadata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOneResponse) ProtoMessage() {}

func (x *FetchOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zookeepermetadata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOneResponse.ProtoReflect.Descriptor instead.
func (*FetchOneResponse) Descriptor() ([]byte, []int) {
	return file_zookeepermetadata_proto_rawDescGZIP(), []int{2}
}

func (x *FetchOneResponse) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type FetchAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchAllRequest) Reset() {
	*x = FetchAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zookeepermetadata_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAllRequest) ProtoMessage() {}

func (x *FetchAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zookeepermetadata_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAllRequest.ProtoReflect.Descriptor instead.
func (*FetchAllRequest) Descriptor() ([]byte, []int) {
	return file_zookeepermetadata_proto_rawDescGZIP(), []int{3}
}

type FetchAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetadataList []*MetadataListItem `protobuf:"bytes,1,rep,name=metadata_list,json=metadataList,proto3" json:"metadata_list,omitempty"`
}

func (x *FetchAllResponse) Reset() {
	*x = FetchAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zookeepermetadata_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAllResponse) ProtoMessage() {}

func (x *FetchAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zookeepermetadata_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAllResponse.ProtoReflect.Descriptor instead.
func (*FetchAllResponse) Descriptor() ([]byte, []int) {
	return file_zookeepermetadata_proto_rawDescGZIP(), []int{4}
}

func (x *FetchAllResponse) GetMetadataList() []*MetadataListItem {
	if x != nil {
		return x.MetadataList
	}
	return nil
}

var File_zookeepermetadata_proto protoreflect.FileDescriptor

var file_zookeepermetadata_proto_rawDesc = []byte{
	0x0a, 0x17, 0x7a, 0x6f, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x7a, 0x6f, 0x6f, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x10,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x53,
	0x4e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x47, 0x53, 0x4e, 0x22, 0x23, 0x0a, 0x0f,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x67, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x67, 0x73,
	0x6e, 0x22, 0x2c, 0x0a, 0x10, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22,
	0x11, 0x0a, 0x0f, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x5c, 0x0a, 0x10, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x7a, 0x6f, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x0c, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74,
	0x32, 0xb5, 0x01, 0x0a, 0x09, 0x5a, 0x6f, 0x6f, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x12, 0x53,
	0x0a, 0x08, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4f, 0x6e, 0x65, 0x12, 0x22, 0x2e, 0x7a, 0x6f, 0x6f,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23,
	0x2e, 0x7a, 0x6f, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x08, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x12,
	0x22, 0x2e, 0x7a, 0x6f, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x7a, 0x6f, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x63, 0x61, 0x6c, 0x6f, 0x67, 0x2f, 0x73, 0x63,
	0x61, 0x6c, 0x6f, 0x67, 0x2f, 0x7a, 0x6f, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zookeepermetadata_proto_rawDescOnce sync.Once
	file_zookeepermetadata_proto_rawDescData = file_zookeepermetadata_proto_rawDesc
)

func file_zookeepermetadata_proto_rawDescGZIP() []byte {
	file_zookeepermetadata_proto_rawDescOnce.Do(func() {
		file_zookeepermetadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_zookeepermetadata_proto_rawDescData)
	})
	return file_zookeepermetadata_proto_rawDescData
}

var file_zookeepermetadata_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_zookeepermetadata_proto_goTypes = []interface{}{
	(*MetadataListItem)(nil), // 0: zookeepermetadata.MetadataListItem
	(*FetchOneRequest)(nil),  // 1: zookeepermetadata.FetchOneRequest
	(*FetchOneResponse)(nil), // 2: zookeepermetadata.FetchOneResponse
	(*FetchAllRequest)(nil),  // 3: zookeepermetadata.FetchAllRequest
	(*FetchAllResponse)(nil), // 4: zookeepermetadata.FetchAllResponse
}
var file_zookeepermetadata_proto_depIdxs = []int32{
	0, // 0: zookeepermetadata.FetchAllResponse.metadata_list:type_name -> zookeepermetadata.MetadataListItem
	1, // 1: zookeepermetadata.ZooKeeper.FetchOne:input_type -> zookeepermetadata.FetchOneRequest
	3, // 2: zookeepermetadata.ZooKeeper.FetchAll:input_type -> zookeepermetadata.FetchAllRequest
	2, // 3: zookeepermetadata.ZooKeeper.FetchOne:output_type -> zookeepermetadata.FetchOneResponse
	4, // 4: zookeepermetadata.ZooKeeper.FetchAll:output_type -> zookeepermetadata.FetchAllResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zookeepermetadata_proto_init() }
func file_zookeepermetadata_proto_init() {
	if File_zookeepermetadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zookeepermetadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zookeepermetadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zookeepermetadata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zookeepermetadata_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zookeepermetadata_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zookeepermetadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zookeepermetadata_proto_goTypes,
		DependencyIndexes: file_zookeepermetadata_proto_depIdxs,
		MessageInfos:      file_zookeepermetadata_proto_msgTypes,
	}.Build()
	File_zookeepermetadata_proto = out.File
	file_zookeepermetadata_proto_rawDesc = nil
	file_zookeepermetadata_proto_goTypes = nil
	file_zookeepermetadata_proto_depIdxs = nil
}
